export * from './IntelligenceEmocional'
export * from './Home'
export * from './Comunication'
export * from './History'
export * from './CardQuiz'
export * from './LogicReasoning'
export * from './ThinkingCritical'
export * from './FinishQuizModal'
